export const REGISTRY_COMPLETED = "REGISTRY_COMPLETED";
export const REGISTRY_ERROR = "REGISTRY_ERROR";

export const LOGIN_OK = "LOGIN_OK";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const AUTHENTICATED_USER = "AUTHENTICATED_USER";
export const LOGOUT_OK = "LOGOUT_OK";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

export const UPLOAD_FILE = "UPLOAD_FILE";
export const UPLOAD_FILE_OK = "UPLOAD_FILE_OK";
export const UPLOAD_FILE_ERROR = "UPLOAD_FILE_ERROR";

export const CREATE_LINK_OK = "CREATE_LINK_OK";
// export const CREATE_LINK_ERROR = "CREATE_LINK_ERROR";

export const CLEAN_STATE = "CLEAN_STATE";

export const AGREGAR_PASSWORD = "AGREGAR_PASSWORD";
export const AGREGAR_DESCARGAS = "AGREGAR_DESCARGAS";
