export const REGISTRY_COMPLETED = "REGISTRY_COMPLETED";
export const REGISTRY_ERROR = "REGISTRY_ERROR";

export const LOGIN_OK = "LOGIN_OK";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const AUTHENTICATED_USER = "AUTHENTICATED_USER";
export const LOGOUT_OK = "LOGOUT_OK";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

export const SUBIR_ARCHIVO = "SUBIR_ARCHIVO";
export const SUBIR_ARCHIVO_EXITO = "SUBIR_ARCHIVO_EXITO";
export const SUBIR_ARCHIVO_ERROR = "SUBIR_ARCHIVO_ERROR";

export const CREAR_ENLACE_EXITO = "CREAR_ENLACE_EXITO";
export const CREAR_ENLACE_ERROR = "CREAR_ENLACE_ERROR";

export const LIMPIAR_STATE = "LIMPIAR_STATE";

export const AGREGAR_PASSWORD = "AGREGAR_PASSWORD";
export const AGREGAR_DESCARGAS = "AGREGAR_DESCARGAS";
